---
parent: "api_v1_projects_projectid_autocodeconfig"
name: "api_v1_projects_projectid_autocodeconfig_get_path_param_null_value_projectId"
description: null
type: "SUITE"
endpoint: "/api/v1/projects/null/autocodeconfig"
method: "GET"
auth: "Default"
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases: []
assertions:
- "@StatusCode != 200"
tags:
- "V1"
authors:
- "FX Bot"
category: "Negative"
severity: "Minor"
inactive: false
policies: null
